package(default_visibility = ["//tensorflow_model_optimization:__subpackages__"])

licenses(["notice"])

py_library(
    name = "collaborative_optimizations",
    srcs = ["__init__.py"],
    srcs_version = "PY3",
    deps = [
        "//tensorflow_model_optimization/python/core/quantization/keras/collaborative_optimizations/cluster_preserve",
        "//tensorflow_model_optimization/python/core/quantization/keras/collaborative_optimizations/prune_preserve",
    ],
)
