# Placeholder: load py_library

package(default_applicable_licenses = ["//tensorflow_model_optimization:license"])

licenses(["notice"])

py_library(
    name = "test_utils_mnist",
    testonly = 1,
    srcs = ["test_utils_mnist.py"],
    # strict_deps = True,
    visibility = ["//visibility:public"],
    deps = [
        # numpy dep1,
        # tensorflow dep1,
        "//tensorflow_model_optimization/python/core/keras:compat",
    ],
)
