package(default_visibility = ["//third_party/tensorflow_model_optimization/python/core/common/keras:__subpackages__"])

licenses(["notice"])  # Apache 2.0

exports_files(["LICENSE"])

py_library(
    name = "wrapper",
    srcs = ["wrapper.py"],
    srcs_version = "PY3",
    deps = [
        # tensorflow dep1,
        "//tensorflow_model_optimization/python/core/common:algorithm",
    ],
)
