# Placeholder: load py_library

package(default_visibility = ["//tensorflow_model_optimization:__subpackages__"])

licenses(["notice"])

py_library(
    name = "quantization",
    srcs = ["__init__.py"],
    strict_deps = True,
    deps = [
        "//tensorflow_model_optimization/python/core/quantization/keras",  # buildcleaner: keep
    ],
)
