package(default_visibility = ["//third_party/tensorflow_model_optimization/python/core/common:__subpackages__"])

licenses(["notice"])  # Apache 2.0

exports_files(["LICENSE"])

py_library(
    name = "algorithm",
    srcs = ["algorithm.py"],
    srcs_version = "PY3",
    deps = [
        # attr dep1,
    ],
)
