package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2.0

py_library(
    name = "tensor_encoding",
    srcs = ["__init__.py"],
    srcs_version = "PY2AND3",
    deps = [
        "//tensorflow_model_optimization/python/core/internal/tensor_encoding/core",
        "//tensorflow_model_optimization/python/core/internal/tensor_encoding/encoders",
        "//tensorflow_model_optimization/python/core/internal/tensor_encoding/stages",
        "//tensorflow_model_optimization/python/core/internal/tensor_encoding/utils",
    ],
)
