# Placeholder: load py_library

package(default_visibility = ["//visibility:public"])

licenses(["notice"])

py_library(
    name = "sparsity",
    srcs = ["__init__.py"],
    strict_deps = True,
    deps = [
        "//tensorflow_model_optimization/python/core/sparsity/keras",  # buildcleaner: keep
    ],
)
