package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2.0

exports_files(["LICENSE"])

py_library(
    name = "python",
    srcs = ["__init__.py"],
    deps = [
        "//tensorflow_model_optimization/python/core",
    ],
)
